export type ShopId = number;
export type ShopName = string;
export type ShopEmail = string;
export type ShopDomain = string;
export type ShopProvince = string;
export type ShopCountry = string;
export type ShopAddress1 = string;
export type ShopZip = string;
export type ShopCity = string;
export type ShopPhone = string;
export type ShopLatitude = number;
export type ShopLongitude = number;
export type ShopPrimaryLocale = string;
export type ShopCreatedAt = string;
export type ShopUpdatedAt = string;

export type Shop = {
  id: ShopId;
  name: ShopName;
  email: ShopEmail;
  domain: ShopDomain;
  province: ShopProvince;
  country: ShopCountry;
  address1: ShopAddress1;
  zip: ShopZip;
  city: ShopCity;
  phone: ShopPhone;
  latitude: ShopLatitude;
  longitude: ShopLongitude;
  primary_locale: ShopPrimaryLocale;
  created_at: ShopCreatedAt;
  updated_at: ShopUpdatedAt;
};
